avs_core/filters/focus.cpp
Used to break some scripts like BalanceBorders
=> Don't use SIMD-optimized horizontal blur on small YV12 clips

distrib/WinInstaller/avisynth+.iss, distrib/WinInstaller/update_git_rev.bat, distrib/WinInstaller/update_git_rev.ps1
This PR fixes:
* the headers not being installed 
* the AVISYNTH_SDK_PATH environment variable not being set
when the Filter SDK component is chosen.
=> Windows Installer: Install Filter SDK Correctly

README.md, avs_core/include/avisynth.h, distrib/ColorPresets/colors_rgb.avsi, distrib/FilterSDK/FilterSDK.htm, distrib/FilterSDK/GettingStartedWithAudio.htm, distrib/FilterSDK/SDKNecessaries.htm, distrib/docs/english/source/avisynthdoc/FilterSDK/FilterSDK.rst, distrib/docs/english/source/avisynthdoc/FilterSDK/GettingStartedWithAudio.rst, distrib/docs/english/source/avisynthdoc/FilterSDK/SDKNecessaries.rst, plugins/DirectShowSource/directshow_source.cpp
I noticed earlier this morning that RC2 had been released a few days ago, so I did the same thing I did for RC1 and looked at what needed to be merged.  The answer is a very underwhelming 'almost nothing', because most of the 14 commits that make up RC2 touch parts that have been removed from AviSynth+ entirely.
```
HTML		0001-corrections.patch
HTML		0003-Fix-No-newline-at-end-of-file.patch
HTML		0013-Use-env-Invoke-ConvertAudio-.-in-example.patch
applies-1	0002-one-instance-of-color_palegoldenrod-removed.patch
applies-2	0006-Add-I420-to-message.patch
rejected-1	0007-Remove-AlignPlanar.patch
rejected-2	0008-Release-candicate-2.patch
rejected-3	0009-Support-2.6-colour-spaces.-Wilbert.patch
rejected-4	0010-Remove-AlignPlanar.patch
rejected-5 …
```
=> Integrate changes from 2.6 RC2

avs_core/core/PluginManager.cpp
Otherwise 64-bit C plugins are rejected as invalid.
(I'd initially tried to use a cleaner approach with *#define*s at the top of PluginManager.cpp, but that didn't pan out, so I resorted to this instead.)
=> avisynth_c: Fix 64-bit C plugin loading

avs_core/core/avisynth.cpp, avs_core/core/parser/script.cpp
For both formats of String() script function: String(float [,formatstring])
=> VSprintf, parser: force decimal separator "." for float formatting (+ PixelType)

avs_core/convert/convert.cpp, avs_core/convert/convert_planar.cpp, avs_core/convert/convert_planar.h, avs_core/core/avisynth.cpp
As 8 bit counterparts, conversions within bit depth. ConvertToYV12/16/24 remained for 8 bit (naming)
Also new: ConvertToY. Though ConvertToY8 silently allows higher bitdepths.
=> 8/16/32 bit ConvertToYUV420/422/444 like ConvertToYV12/YV16/YV24

avs_core/filters/combine.cpp, avs_core/filters/focus.cpp
std::vector is as fast as (or a bit faster than) alloca in these days.
there is no reason to use alloca instead of safety vector.
=> Replace alloca to std::vector.

avs_core/filters/resample.cpp, avs_core/filters/resample.h
According to test on Sandy Bridge, Ivy Bridge and Nehalem, this actually beats or as fast as 2.6a5 resizers now.
Improvements:
- Faster horizontal scaling on most resizers on CPU with SSSE3 support and mod4-clip (both luma and chroma) on planar colorspace.
- Much faster horizontal point scaling
=> Faster horizontal resizer

avs_core/core/parser/scriptparser.cpp, avs_core/core/parser/scriptparser.h
As discussed in https://github.com/AviSynth/AviSynthPlus/commit/24bd8412207a8b9f068218bce38e952bc30fdf9f.
=> Use user-defined literals for multi-character tokens

avs_core/CMakeLists.txt, avs_core/avisynth.pc.in
add missing install rule for install the pkg-config file
~~because i'm not sure if is useful in windows, only install the file if is builded on unix systems (bsd(?) & linux & macos)~~
=> Install pkg-config file if is builded on unix system

CMakeLists.txt, avs_core/CMakeLists.txt, avs_core/avisynth.pc.in, plugins/ConvertStacked/CMakeLists.txt, plugins/DirectShowSource/CMakeLists.txt, plugins/ImageSeq/CMakeLists.txt, plugins/Shibatch/CMakeLists.txt, plugins/TimeStretch/CMakeLists.txt, plugins/VDubFilter/CMakeLists.txt, plugins/VFAPIFilter/CMakeLists.txt
See https://cmake.org/cmake/help/v3.8/module/GNUInstallDirs.html
This get to Linux dristribution like Gentoo can change the library, binary and header paths
For example, Gentoo uses `foo/lib` as path for 32-bit libaries and `foo/lib64` for 64-bits
Use `-DCMAKE_INSTALL_LIBDIR` `-DCMKE_INSTALL_INCLUDEDIR` and `-DCMAKE_INSTALL_BINDIR` change
the default behavior.
The use of `-DCMAKE_INSTALL_PREFIX` is untouched
=> Use cmake GNUInstallDirs

CMakeLists.txt
Both Windows XP and the vc141_xp toolchain have been deprecated for a long time. It requires manual installation an extra component in Visual Studio. This force override simply breaks normal users who only install default toolchain which does not have vc141_xp.
We should not force the user to use deprecated unmaintained tools. Whoever need to build binary for XP should understand what they are doing. They should be able to install those tools by themselves, and specify `CMAKE_GENERATOR_TOOLSET`.
=> Remove the force override to XP toolchain

CMakeLists.txt
~~~
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/GNUInstallDirs.cmake:225 (message):
Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
target architecture is known.  Please enable at least one language before
including GNUInstallDirs.
Call Stack (most recent call first):
CMakeLists.txt:31 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
~~~
=> Silence cmake warning about gnuinstaldirs

avs_core/CMakeLists.txt
It triggered warnings on GCC 8.3 on Debian buster, where CMAKE_COMPILER_IS_GNUCC is not defined due to, probably, no C compiler is checked for explicitly claimed CXX projects, as a result of 8d179bf9c1326839adc9d243a74037308985b968.
=> CMakeLists: check correct flag on linking to stdc++fs

avs_core/core/PluginManager.cpp
Caused by a typo in an array name.
By the way, is that comparison actually case insensitive? The comment doesn't tell why.
=> posix: fix crash when autoloading imports

avs_core/convert/convert_audio.cpp
The float-32 and 32-float was forgotten.
=> ConvertAudio: add missing AVX2 calls

.github/workflows/build.yml
This adds a GitHub action workflow file which on every commit
triggers an MSVC release build for x86/x64. The binaries and
readme files are then stored as a GitHub action artifact.
These packages can be used for manual testing by AviSynth
users.
The workflow could also be extended to build complete
installers via InnoSetup.
=> Add a GitHub action workflow

avs_core/filters/source.cpp
These are from the RP 219-2014, but those are also on Wikipedia now:
https://en.wikipedia.org/wiki/SMPTE_color_bars
Those values here used BT.601 matrix coeff., which is wrong.
=> ColorBarsHD: use BT.709-2 for +I, not BT.601

avs_core/avisynth.pc.in
``${exec_prefix}`` is only meant to be used for libraries and not for non-machine specific files such as headers; see https://www.gnu.org/prep/standards/html_node/Directory-Variables.html and also the example in the pkg-config docs: https://people.freedesktop.org/~dbn/pkg-config-guide.html#using
Some systems may override the prefixes when relocating the libraries. For instance, vcpkg relocates the libraries (but not the headers) and adjusts the .pc file accordingly to allow simultaneous installation of release and debug builds. (This patch thus fixes a vcpkg compile error when using pkg-config to link against avs+.)
=> pkg-config: use prefix for includedir instead of exec_prefix

avs_core/filters/turn.cpp
```
/usr/bin/ld: CMakeFiles/AvsCore.dir/filters/intel/turn_sse.cpp.o: in function `turn_left_rgb64_sse2(unsigned char const*, unsigned char*, int, int, int, int)':
turn_sse.cpp:(.text+0xa34): undefined reference to `void turn_right_plane_c<unsigned long>(unsigned char const*, unsigned char*, int, int, int, int)'
/usr/bin/ld: CMakeFiles/AvsCore.dir/filters/intel/turn_sse.cpp.o: in function `turn_right_rgb64_sse2(unsigned char const*, unsigned char*, int, int, int, int)':
turn_sse.cpp:(.text+0xbd3): undefined reference to `void turn_right_plane_c<unsigned long>(unsigned char const*, unsigned char*, int, int, int, int)'
/usr/bin/ld: CMakeFiles/AvsCore.dir/filters/intel/turn_sse.cpp.o: in function `turn_left_rgb64_sse2(unsigned char const*, unsigned char*, int, int, int, int)': …
```
=> Fix build failure on Linux when optimizations are enabled

avs_core/core/PluginManager.cpp, avs_core/core/avisynth.cpp, avs_core/core/parser/tokenizer.cpp
* 'readlink' does not null-terminate the buffer, so zero-initialize it. We could check the result of 'readlink', but since an ifdef is involved, this solution is simpler.
* 'ScriptEnvironment::LogLevel' and 'ScriptEnvironment::cacheMode'.
* 'Tokenizer::type' when cloning a Tokenizer.
=> Fix some uninitialized values

avs_core/core/avisynth_c.cpp, avs_core/include/avisynth.h, avs_core/include/avisynth_c.h
Fix the error check.
Return result consistent with the CPP API equivalent function.
=> Fix: C API avs_prop_get_data

distrib/docs/english/source/avisynthdoc/changelist373.rst, plugins/TimeStretch/TimeStretch.cpp
Takes care of https://github.com/AviSynth/AviSynthPlus/issues/278 - hope I didn't break anything.
=> Add TimeStretch overload with rational pair arguments.

avs_core/include/avisynth.h
- `struct VideoInfo`: Either each value in the comments misses one `0` (covered by PR), or everything else is wrong.
- See commit messages for more.
=> Wrong values in comments (or wrong values?)

distrib/docs/english/source/avisynthdoc/FilterSDK/Cplusplus_api.rst
In `avisynth.h`, it can only be found in `INeoEnv`, not `IScriptEnvironment`.
Where did it come from? Even IanB talks about it in his post linked for [`PushContext()`](https://avisynthplus.readthedocs.io/en/latest/avisynthdoc/FilterSDK/Cplusplus_api.html#pushcontext).
Was it once part of `IScriptEnvironment`? I thought removing functions invalidates the vtable?
=> Remove `PopContextGlobal()` from `Cplusplus_api.rst`

avs_core/core/interface.cpp, avs_core/include/avisynth.h, distrib/Readme/readme_history.txt
See #314.
In `class AVSValue` in `avisynth.h`, I had to write
```cpp
AvsValueType GetType() const AVS_BakedCode( return AVS_LinkCallOptDefault(AVSValue_GetType, VALUE_TYPE_UNDEFINED) )
```
instead of
```cpp
AvsValueType GetType() const AVS_BakedCode( return AVS_LinkCall(AVSValue_GetType) )
```
to get it to work. Same as with `PDevice::GetType()`. I don't know if it's the only way to do it.
=> Added `AVSValue::GetType`

avs_core/convert/convert.cpp, avs_core/convert/convert_bits.cpp, avs_core/core/avisynth.cpp, avs_core/core/interface.cpp, avs_core/filters/planeswap.cpp, avs_core/filters/source.cpp, avs_core/include/avisynth.h, avs_core/include/avisynth_c.h, distrib/Readme/readme_history.txt, plugins/ConvertStacked/ConvertStacked.cpp
Closes #317.
Don't forget to change the line in `struct AVS_Linkage` with the `TEMPORARY ENTRY` comment when resolving the conflict there that would happen anyway after merging #331.
=> Added `VideoFrame::GetPixelType()`.

CMakeLists.txt
Add support for Intel C++ Compiler 2024.
Set /fp:precise for IntelLLVM compilers.
=> CMakeLists: add the latest Intel compiler

distrib/docs/english/source/avisynthdoc/syntax/syntax_internal_functions_boolean.rst
I've found a typo in the naming of the function `VarExist` in page [AviSynth Syntax - Boolean functions](https://avisynthplus.readthedocs.io/en/latest/avisynthdoc/syntax/syntax_internal_functions_boolean.html#varexists).
In case of doubts, please refer to the older wiki that follows the correct naming: http://avisynth.nl/index.php/Internal_functions#VarExist.
=> fix "VarExists" typo

avs_core/avisynth.pc.in, avs_core/avisynth_conf.h.in
When CMAKE_INSTALL_\<dir> is an absolute path the build fails, due to libdir and includedir being being created by concatenating prefix and  CMAKE_INSTALL_\<dir>, instead using CMAKE_INSTALL_FULL_\<dir> which check if CMAKE_INSTALL_\<dir> is an absolute path and if not concatenates it with CMAKE_INSTALL_PREFIX.
I encountered this issue while packing AviSynthPlus for nixpkgs.
=> Fix when building with absolute paths

plugins/TimeStretch/SoundTouch/FIRFilter.cpp, plugins/TimeStretch/SoundTouch/STTypes.h
- Increased the max number of channels to 32ch from the old limit of 16ch.
- Removed the hardcoded 16ch check in FIRFilter.cpp to make it use the SOUNDTOUCH_MAX_CHANNELS variable defined in STTypes.h instead.
Both of those changes follow what was actually committed by Olli Parviainen, the SoundTouch maintainer, in the main repo: https://codeberg.org/soundtouch/soundtouch/commit/ddf28667c9f52f30573853c8177e77149829fa7c
This was tracked here as part of this conversation: https://codeberg.org/soundtouch/soundtouch/issues/38
=> Increased the maximum number of channels in SoundTouch from 16ch to 32ch

CMakeLists.txt
mingwXX/ucrt64 `vfw.h` has already defined these.
Fixes https://github.com/AviSynth/AviSynthPlus/issues/242 and https://github.com/AviSynth/AviSynthPlus/issues/342#issuecomment-1464720668.
=> Fix mingwXX/ucrt64 redefinitions

avs_core/include/avs/config.h
[LoongArch](https://docs.kernel.org/arch/loongarch/introduction.html) is a new RISC ISA developed by loongson. There are already a lot of [community support and testing](https://www.phoronix.com/search/LoongArch) about it.
This PR adds the support of LoongArch. I've tested it with Arch Linux's loong64 port, and the build process **succeeded**. ([view the log](https://gist.github.com/wszqkzqk/d551c8c86aaa8e786b236bb69d51a3c2))
=> Add LoongArch support

avs_core/core/avisynth.cpp, avs_core/core/cache.cpp
I am a member of Microsoft vcpkg, due to there are new changes merged by microsoft/STL#5105, which revealed a conformance issue in `AviSynthPlus`. It must add include `<chrono>` to fix this error.
Compiler error with this STL change:
```
D:\b\avisynthplus\src\v3.7.3-01e1867324.clean\avs_core\core\cache.cpp(181): error C2039: 'high_resolution_clock': is not a member of 'std::chrono'
D:\b\avisynthplus\src\v3.7.3-01e1867324.clean\avs_core\core\avisynth.cpp(911): error C2039: 'high_resolution_clock': is not a member of 'std::chrono'
```
=> Include `<chrono>` for high_resolution_clock

avs_core/include/avisynth_c.h
Fixes:
```
/opt/ffbuild/include/avisynth/avisynth_c.h:1915:22: error: no member named 'avs_get_as_array' in 'struct AVS_Library'
1915 |   AVSC_LOAD_FUNC_OPT(avs_get_as_array);
|   ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/opt/ffbuild/include/avisynth/avisynth_c.h:1715:52: note: expanded from macro 'AVSC_LOAD_FUNC_OPT'
1715 | #define AVSC_LOAD_FUNC_OPT(name) AVSC_DO_LOAD_FUNC(name, 1)
|                                  ~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ffbuild/include/avisynth/avisynth_c.h:1710:12: note: expanded from macro 'AVSC_DO_LOAD_FUNC'
1710 |   library->name = (name##_func) GetProcAddress(library->handle, AVSC_STRINGIFY(name));\
|   ~~~~~~~  ^
/opt/ffbuild/include/avisynth/avisynth_c.h:1915:22: error: no member named 'avs_get_as_array' in 'struct AVS_Library'
1915 | …
```
=> Fix missing semicolon in C header
